### ISSUE TITLE
Error becaused by multiple line LaTeX formula

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/AGSBS-infrastructure#29]
The conversion causes an exception, when the LaTeX formula has multiple lines
See example

```
$$
p(x_i)=\frac{1}{N}\; 
\text{for} i=1,2,...,N
$$ 
```

The trace back is

    error:
      path: E:\Material\test
      message:
    
    Traceback (most recent call last):

      File "gladtex.py", line 261, in <module>

      File "gladtex.py", line 164, in run

      File "gladtex.py", line 207, in convert_images

      File "Z:\home\johnDoe\daten\quellen\gladtex\gleetex\convenience.py", line 87, in convert_all

      File "Z:\home\johnDoe\daten\quellen\gladtex\gleetex\convenience.py", line 136, in _convert_concurrently

      File "C:\Python34\lib\concurrent\futures\_base.py", line 395, in result

      File "C:\Python34\lib\concurrent\futures\_base.py", line 354, in __get_result

      File "C:\Python34\lib\concurrent\futures\thread.py", line 54, in run

      File "Z:\home\johnDoe\daten\quellen\gladtex\gleetex\convenience.py", line 178, in convert

      File "Z:\home\johnDoe\daten\quellen\gladtex\gleetex\image.py", line 197, in convert

      File "Z:\home\johnDoe\daten\quellen\gladtex\gleetex\image.py", line 135, in create_dvi

      File "Z:\home\johnDoe\daten\quellen\gladtex\gleetex\image.py", line 34, in proc_call

      File "C:\Python34\lib\subprocess.py", line 962, in communicate

      File "C:\Python34\lib\subprocess.py", line 1198, in _communicate

    TypeError: 'str' does not support the buffer interface

If the formula is in one line it works good.

**Comment by humenda** [comment]
This was a GladTeX issue. It has been fixed upstream.
