### ISSUE TITLE
build_windows_installer.py causes FileExistsError 'COPYING' -> 'COPYING.txt'

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/AGSBS-infrastructure#34]
When I try to build the installer i got this traceback

```
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Github\agsbs-infrastructure\installer\build_windows_installer.py", line 258, in <module>
    build_installer()
  File "C:\Users\Administrator\Documents\Github\agsbs-infrastructure\installer\build_windows_installer.py", line 221, in build_installer
    os.rename('COPYING', 'COPYING.txt')
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'COPYING' -> 'COPYING.txt'
```

If I remove line 221 in build_windows_installer.py, it works fine.

**Comment by humenda** [comment]
Removing lines without purpose is not a good idea. This line adds a file extension, which helps to open the file on Windows. It seems to be a glitch with the (Windows) Python interface, that adding a file extension is treated as the same file name. I've reworked the code, please pull and test.
