### ISSUE TITLE
checking installation on OS X

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/AGSBS-infrastructure#46]
CLI on Mac Book 

command `$ matuc -h` causes this traceback

```

Traceback (most recent call last):
  File "/usr/local/bin/matuc", line 18, in <module>
    import MAGSBS
  File "/usr/local/lib/python3.6/site-packages/MAGSBS/__init__.py", line 6, in <module>
    from . import master
  File "/usr/local/lib/python3.6/site-packages/MAGSBS/master.py", line 14, in <module>
    from . import pandoc
ImportError: cannot import name 'pandoc'
```

**Comment by humenda** [comment]
The README gives details on the installation, mentioning to install pandocfilters beforehand.

**Comment by jevo** [comment]
The folder MAGSBS/pandoc is not listed in the setup.py
