### ISSUE TITLE
Error depending on Python version 3.6.3

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/AGSBS-infrastructure#49]
Parameter of the system:

OS: Mac OS X 10.13.3
Python3: Python 3.6.3

Try execute the commando  in terminal and atom via F5.

`matuc_js mk "/Users/voegler/Documents/atom_test/k01" `

causes this exception

```
Traceback (most recent call last):
  File "/usr/local/bin/matuc_js", line 50, in <module>
    main_inst.run(sys.argv)
  File "/Users/admin/github/AGSBS-infrastructure/matuc_impl/__init__.py", line 192, in run
    ret = func(invokation_command, args[2:])
  File "/Users/admin/github/AGSBS-infrastructure/matuc_impl/__init__.py", line 485, in handle_mk
    self.output_formatter.emit_result(format_errors())
  File "/Users/admin/github/AGSBS-infrastructure/matuc_impl/__init__.py", line 449, in format_errors
    mistakes = mistkerl.run(options.input)
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/mistkerl.py", line 119, in run
    self.__run_filters_on_file(file_path, paragraphs)
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/mistkerl.py", line 179, in __run_filters_on_file
    for issue in self.get_issues(MistakeType.formulas, file_path):
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/mistkerl.py", line 80, in get_issues
    return list(i for i in (i() for i in issues) # instanciate
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/mistkerl.py", line 80, in <genexpr>
    return list(i for i in (i() for i in issues) # instanciate
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/mistkerl.py", line 80, in <genexpr>
    return list(i for i in (i() for i in issues) # instanciate
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/latex.py", line 35, in __init__
    self.pattern = re.compile(r".*(\left|\big|\Big)\(.*?begin{(array|matrix)")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \l at position 3
```

**Comment by jevo** [comment]
After a downgrade to Python 3.5.4 it works.

**Comment by humenda** [comment]
Thanks for the investigation. This has been a slumbering bug for a long while
now and only Python 3.6's strictness has revealed it. It would now be very
helpful if you could please re-test with Python 3.6. There is a chance that more
of these regular expression bugs exist.

**Comment by xplhak** [comment]
I did the testing with Python 3.6.4 on Windows and it works now.

**Comment by humenda** [comment]
Thanks, good news!
